name: Copy Files from smartchat to insta

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files from smartchat to insta
        run: |
          mkdir -p insta
          cp -r smartchat/* insta/

      - name: Print Git remote URL
        run: git remote -v

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://$GH_PAT@github.com/sogreatcomputerinstitute/smartchatreal-v.1.git
          git add insta
          git commit -m "Automated copy of files from smartchat to insta"
          git push origin main
